root = "."
tmp_dir = "tmp"

[build]
  bin = "tmp/main"
  cmd = ""  # Prevent building, just restart the server
  log = "debug"
  include = ["*.go"]
  exclude = ["tmp", "vendor"]

[color]
  main = "yellow"
  watcher = "cyan"
  build = "green"
  log = "white"